name: 'Release Train Action'
description: 'Automated release train for mobile apps'
inputs:
  command:
    description: 'Options: release-train; tag; hotfix; pr-linter'
    required: true
  token:
    description: 'GITHUB_TOKEN'
    required: true
  release-owner:
    description: 'User or team that will be added as reviewer to release PRs'
    required: false
  title-lint-message:
    description: 'tbd'
    required: false
  base-branch-lint-message:
    description: 'tbd'
    required: false

  destination-branch:
    description: 'tbd'
    required: false
  current-branch:
    description: 'tbd'
    required: false
  pr-title:
    description: 'tbd'
    required: false

  release-branch:
    description: 'TBD'
    required: false
    default: 'release-train'
  development-branch:
    description: 'TBD'
    required: false
    default: 'develop'
  stable-branch:
    description: 'TBD'
    required: false
    default: 'master'
runs:
  using: "composite"
  steps:
    - name: Run workflow
      shell: bash
      run: |
        echo "configs"
        export ROOT_PATH=${{ github.action_path }}
        export DESTINATION_BRANCH=${{ inputs.development-branch }}
        export CURRENT_BRANCH=${{ inputs.current-branch }}
        export PR_TITLE=${{ inputs.pr-title }}

        echo "inputs"
        export GH_CLI_TOKEN=${{ inputs.token }}
        export COMMAND=${{ inputs.command }}

        export RELEASE_BRANCH=${{ inputs.release-branch }}
        export DEVELOPMENT_BRANCH=${{ inputs.development-branch }}
        export STABLE_BRANCH=${{ inputs.stable-branch }}
        
        export RELEASE_OWNER=${{ inputs.release-owner }}

        cat > TITLE_LINT_MESSAGE.md <<- EOM
        ${{ inputs.title-lint-message }}
        EOM

        cat > BASE_BRANCH_LINT_MESSAGE.md <<- EOM
        ${{ inputs.base-branch-lint-message }}
        EOM

        echo "run action"
        $ROOT_PATH/action.sh
        exit $?