#!/bin/bash

source $ROOT_PATH/cmds.sh

setup_git
check_for_new_changes_available
login_to_github_cli
switch_to_release_branch
save_current_release_notes
run_standard_version
update_with_base_branch
open_pull_requests
create_tag_for_release_candidate